# sensor_msgs/Image image_front
# sensor_msgs/Image image_back
# sensor_msgs/Image image_left
# sensor_msgs/Image image_right

int32   TimeStamp
int32   coord_X
int32   coord_Y
int32   coord_Z
int32   image_begin_sec
int32   image_begin_usec
int32   image_end_sec
int32   image_end_usec

float32 expo_front_s
float32 expo_front_l
float32 expo_back_s
float32 expo_back_l
float32 expo_left_s
float32 expo_left_l
float32 expo_right_s
float32 expo_right_l